package com.qtone.wxq.eye.store.mysql.presist.mapping;

import com.qtone.wxq.eye.store.mysql.presist.model.AnnotationEntry;
import com.qtone.wxq.eye.store.mysql.presist.model.AnnotationEntryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AnnotationEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int countByExample(AnnotationEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int deleteByExample(AnnotationEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int insert(AnnotationEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int insertSelective(AnnotationEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    List<AnnotationEntry> selectByExample(AnnotationEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    AnnotationEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") AnnotationEntry record, @Param("example") AnnotationEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int updateByExample(@Param("record") AnnotationEntry record, @Param("example") AnnotationEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int updateByPrimaryKeySelective(AnnotationEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table annotation
     *
     * @mbggenerated Wed Feb 22 10:30:03 CST 2017
     */
    int updateByPrimaryKey(AnnotationEntry record);
}