package com.qtone.wxq.eye.store.mysql.presist.mapping;

import com.qtone.wxq.eye.store.mysql.presist.model.SpanEntry;
import com.qtone.wxq.eye.store.mysql.presist.model.SpanEntryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpanEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int countByExample(SpanEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int deleteByExample(SpanEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int insert(SpanEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int insertSelective(SpanEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    List<SpanEntry> selectByExample(SpanEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    SpanEntry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") SpanEntry record, @Param("example") SpanEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int updateByExample(@Param("record") SpanEntry record, @Param("example") SpanEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int updateByPrimaryKeySelective(SpanEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    int updateByPrimaryKey(SpanEntry record);
}