package com.qtone.wxq.eye.store.mysql.presist.mapping;

import com.qtone.wxq.eye.store.mysql.presist.model.TraceEntry;
import com.qtone.wxq.eye.store.mysql.presist.model.TraceEntryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TraceEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int countByExample(TraceEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int deleteByExample(TraceEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int insert(TraceEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int insertSelective(TraceEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    List<TraceEntry> selectByExample(TraceEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    TraceEntry selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraceEntry record, @Param("example") TraceEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int updateByExample(@Param("record") TraceEntry record, @Param("example") TraceEntryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int updateByPrimaryKeySelective(TraceEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trace
     *
     * @mbggenerated Wed Feb 22 10:29:21 CST 2017
     */
    int updateByPrimaryKey(TraceEntry record);
}