package com.qtone.wxq.eye.store.mysql.presist.model;

public class SpanEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.id
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.name
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.traceId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    private Long traceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.parentId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.spanId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    private Long spanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.service
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    private String service;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.id
     *
     * @return the value of span.id
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.id
     *
     * @param id the value for span.id
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.name
     *
     * @return the value of span.name
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.name
     *
     * @param name the value for span.name
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.traceId
     *
     * @return the value of span.traceId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public Long getTraceid() {
        return traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.traceId
     *
     * @param traceid the value for span.traceId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public void setTraceid(Long traceid) {
        this.traceid = traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.parentId
     *
     * @return the value of span.parentId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.parentId
     *
     * @param parentid the value for span.parentId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.spanId
     *
     * @return the value of span.spanId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public Long getSpanid() {
        return spanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.spanId
     *
     * @param spanid the value for span.spanId
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public void setSpanid(Long spanid) {
        this.spanid = spanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.service
     *
     * @return the value of span.service
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.service
     *
     * @param service the value for span.service
     *
     * @mbggenerated Fri Feb 17 18:33:33 CST 2017
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }
}