package com.qtone.wxq.eye.store.mysql.presist.model;

public class SpanEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.trace_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    private String traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.parent_span_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    private String parentSpanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.span_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    private String spanId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.id
     *
     * @return the value of span.id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.id
     *
     * @param id the value for span.id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.trace_Id
     *
     * @return the value of span.trace_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.trace_Id
     *
     * @param traceId the value for span.trace_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId == null ? null : traceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.parent_span_Id
     *
     * @return the value of span.parent_span_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public String getParentSpanId() {
        return parentSpanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.parent_span_Id
     *
     * @param parentSpanId the value for span.parent_span_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void setParentSpanId(String parentSpanId) {
        this.parentSpanId = parentSpanId == null ? null : parentSpanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.span_Id
     *
     * @return the value of span.span_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public String getSpanId() {
        return spanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.span_Id
     *
     * @param spanId the value for span.span_Id
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void setSpanId(String spanId) {
        this.spanId = spanId == null ? null : spanId.trim();
    }
}