package com.qtone.wxq.eye.store.mysql.presist.model;

public class SpanEntry {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.id
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.traceId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    private String traceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.parentId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column span.spanId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    private String spanid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.id
     *
     * @return the value of span.id
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.id
     *
     * @param id the value for span.id
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.traceId
     *
     * @return the value of span.traceId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public String getTraceid() {
        return traceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.traceId
     *
     * @param traceid the value for span.traceId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public void setTraceid(String traceid) {
        this.traceid = traceid == null ? null : traceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.parentId
     *
     * @return the value of span.parentId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.parentId
     *
     * @param parentid the value for span.parentId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column span.spanId
     *
     * @return the value of span.spanId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public String getSpanid() {
        return spanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column span.spanId
     *
     * @param spanid the value for span.spanId
     *
     * @mbggenerated Wed Feb 22 10:19:41 CST 2017
     */
    public void setSpanid(String spanid) {
        this.spanid = spanid == null ? null : spanid.trim();
    }
}