package com.qtone.wxq.eye.store.mysql.presist.model;

import java.util.ArrayList;
import java.util.List;

public class SpanEntryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public SpanEntryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("span.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("span.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("span.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("span.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("span.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("span.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("span.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("span.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("span.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("span.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("span.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("span.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTraceIdIsNull() {
            addCriterion("span.trace_Id is null");
            return (Criteria) this;
        }

        public Criteria andTraceIdIsNotNull() {
            addCriterion("span.trace_Id is not null");
            return (Criteria) this;
        }

        public Criteria andTraceIdEqualTo(String value) {
            addCriterion("span.trace_Id =", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotEqualTo(String value) {
            addCriterion("span.trace_Id <>", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdGreaterThan(String value) {
            addCriterion("span.trace_Id >", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdGreaterThanOrEqualTo(String value) {
            addCriterion("span.trace_Id >=", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdLessThan(String value) {
            addCriterion("span.trace_Id <", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdLessThanOrEqualTo(String value) {
            addCriterion("span.trace_Id <=", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdLike(String value) {
            addCriterion("span.trace_Id like", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotLike(String value) {
            addCriterion("span.trace_Id not like", value, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdIn(List<String> values) {
            addCriterion("span.trace_Id in", values, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotIn(List<String> values) {
            addCriterion("span.trace_Id not in", values, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdBetween(String value1, String value2) {
            addCriterion("span.trace_Id between", value1, value2, "traceId");
            return (Criteria) this;
        }

        public Criteria andTraceIdNotBetween(String value1, String value2) {
            addCriterion("span.trace_Id not between", value1, value2, "traceId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdIsNull() {
            addCriterion("span.parent_span_Id is null");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdIsNotNull() {
            addCriterion("span.parent_span_Id is not null");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdEqualTo(String value) {
            addCriterion("span.parent_span_Id =", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdNotEqualTo(String value) {
            addCriterion("span.parent_span_Id <>", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdGreaterThan(String value) {
            addCriterion("span.parent_span_Id >", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdGreaterThanOrEqualTo(String value) {
            addCriterion("span.parent_span_Id >=", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdLessThan(String value) {
            addCriterion("span.parent_span_Id <", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdLessThanOrEqualTo(String value) {
            addCriterion("span.parent_span_Id <=", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdLike(String value) {
            addCriterion("span.parent_span_Id like", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdNotLike(String value) {
            addCriterion("span.parent_span_Id not like", value, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdIn(List<String> values) {
            addCriterion("span.parent_span_Id in", values, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdNotIn(List<String> values) {
            addCriterion("span.parent_span_Id not in", values, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdBetween(String value1, String value2) {
            addCriterion("span.parent_span_Id between", value1, value2, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andParentSpanIdNotBetween(String value1, String value2) {
            addCriterion("span.parent_span_Id not between", value1, value2, "parentSpanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdIsNull() {
            addCriterion("span.span_Id is null");
            return (Criteria) this;
        }

        public Criteria andSpanIdIsNotNull() {
            addCriterion("span.span_Id is not null");
            return (Criteria) this;
        }

        public Criteria andSpanIdEqualTo(String value) {
            addCriterion("span.span_Id =", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdNotEqualTo(String value) {
            addCriterion("span.span_Id <>", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdGreaterThan(String value) {
            addCriterion("span.span_Id >", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdGreaterThanOrEqualTo(String value) {
            addCriterion("span.span_Id >=", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdLessThan(String value) {
            addCriterion("span.span_Id <", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdLessThanOrEqualTo(String value) {
            addCriterion("span.span_Id <=", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdLike(String value) {
            addCriterion("span.span_Id like", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdNotLike(String value) {
            addCriterion("span.span_Id not like", value, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdIn(List<String> values) {
            addCriterion("span.span_Id in", values, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdNotIn(List<String> values) {
            addCriterion("span.span_Id not in", values, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdBetween(String value1, String value2) {
            addCriterion("span.span_Id between", value1, value2, "spanId");
            return (Criteria) this;
        }

        public Criteria andSpanIdNotBetween(String value1, String value2) {
            addCriterion("span.span_Id not between", value1, value2, "spanId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table span
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 22 10:29:46 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table span
     *
     * @mbggenerated Wed Feb 22 10:29:46 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}